# Generated by Django 4.0.2 on 2022-02-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('startingBid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imageLink', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
