# Generated by Django 4.0.3 on 2022-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='userId',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageLink',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
