# Generated by Django 4.0.3 on 2022-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_userid_listing_user_alter_listing_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageLink',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
