# Generated by Django 4.0.3 on 2022-04-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'listing')},
        ),
    ]
